from enum import Enum


class LocationType(str, Enum):
    OUTSIDE_SCHOOL = "OUTSIDE_SCHOOL"
    WITHIN_SCHOOL = "WITHIN_SCHOOL"


class AreaType(str, Enum):
    CLASSROOM = "CLASSROOM"
    CAFETERIA = "CAFETERIA"
    PLAYGROUND = "PLAYGROUND"
    HALLWAY = "HALLWAY"
    BATHROOM = "BATHROOM"
    BUS_AREA = "BUS_AREA"
    SPORTS_FIELD = "SPORTS_FIELD"
    COMPUTER_LAB = "COMPUTER_LAB"
    LIBRARY = "LIBRARY"
    OTHER = "OTHER"


class AnonymityLevel(str, Enum):
    COMPLETE_ANONYMOUS = "COMPLETE_ANONYMOUS"
    STUDENT_SUBJECT_ONLY = "STUDENT_SUBJECT_ONLY"
    HIDE_FROM_PARENTS = "HIDE_FROM_PARENTS"
    DONT_HIDE_IDENTITY = "DONT_HIDE_IDENTITY"


class PrivacyLevel(str, Enum):
    LEVEL_1 = "LEVEL_1"
    LEVEL_2 = "LEVEL_2"


class CharityInvolvement(str, Enum):
    ALREADY_INFORMED = "ALREADY_INFORMED"
    INFORM_NOW = "INFORM_NOW"
    MAYBE_LATER = "MAYBE_LATER"
    NO = "NO"


class CharityType(str, Enum):
    COUNSELLING_SUPPORT = "COUNSELLING_SUPPORT"
    CRISIS_INTERVENTION = "CRISIS_INTERVENTION"
    FAMILY_SUPPORT = "FAMILY_SUPPORT"
    MENTAL_HEALTH = "MENTAL_HEALTH"
    ANTI_BULLYING_PARTNER = "ANTI_BULLYING_PARTNER"
    COMMUNITY_SUPPORT = "COMMUNITY_SUPPORT"


class PoliceInvolvement(str, Enum):
    ALREADY_REPORTED = "ALREADY_REPORTED"
    MAYBE_LATER = "MAYBE_LATER"
    NO = "NO"


class ResolutionDesired(str, Enum):
    ADMIN_DISCRETION = "ADMIN_DISCRETION"
    DISCIPLINE_PER_CONDUCT_POLICY = "DISCIPLINE_PER_CONDUCT_POLICY"
    CLASS_WIDE_INTERVENTION_NO_ID = "CLASS_WIDE_INTERVENTION_NO_ID"
    DISCIPLINE_AND_RESTORATIVE_CIRCLE = "DISCIPLINE_AND_RESTORATIVE_CIRCLE"


class CaseStatus(str, Enum):
    PENDING = "PENDING"
    RESOLVED = "RESOLVED"


class PersonRelationship(str, Enum):
    SCHOOLMATE = "SCHOOLMATE"
    EXTERNAL_STUDENT = "EXTERNAL_STUDENT"
    OTHERS = "OTHERS"


class PersonType(str, Enum):
    PARENT = "PARENT"
    FAMILY_MEMBER = "FAMILY_MEMBER"
    STAFF = "STAFF"
    COMMUNITY_MEMBER = "COMMUNITY_MEMBER"
    CONTRACTOR_VISITOR = "CONTRACTOR_VISITOR"
    ONLINE_PERSON = "ONLINE_PERSON"
    STRANGER = "STRANGER"
    OTHER = "OTHER"


class WitnessCoverage(str, Enum):
    ENTIRE_INCIDENT = "ENTIRE_INCIDENT"
    PARTIALLY = "PARTIALLY"
    ONLY_HEARD = "ONLY_HEARD"
    NOT_SURE = "NOT_SURE"


class WitnessReliability(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class RelationshipToVictim(str, Enum):
    CLASSMATE = "CLASSMATE"
    FRIEND = "FRIEND"
    TEAM_MEMBER = "TEAM_MEMBER"
    SIBLING = "SIBLING"
    NO_RELATIONSHIP = "NO_RELATIONSHIP"
    UNKNOWN = "UNKNOWN"


class WasPresent(str, Enum):
    YES = "YES"
    PARTIALLY = "PARTIALLY"
    NO = "NO"
    UNKNOWN = "UNKNOWN"
